In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
%matplotlib inline
import seaborn as sn

In [78]:
df=pd.read_csv("/content/insurance_data.csv")
print(df)

    age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45         

In [79]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [80]:
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))

In [81]:
data = df.drop(['bought_insurance'], axis=1)

In [82]:
feature_set = data.to_numpy()
labels = df.bought_insurance.to_numpy()
labels = labels.reshape(28,1)
print(feature_set)
print(labels)

[[22  1]
 [25  0]
 [47  1]
 [52  0]
 [46  1]
 [56  1]
 [55  0]
 [60  0]
 [62  1]
 [61  1]
 [18  1]
 [28  1]
 [27  0]
 [29  0]
 [49  1]
 [55  1]
 [25  0]
 [58  1]
 [19  0]
 [18  1]
 [21  1]
 [26  0]
 [40  1]
 [45  1]
 [50  1]
 [54  1]
 [23  1]
 [46  1]]
[[0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]


In [89]:
np.random.seed(42)
weights = np.random.rand(2,1)
print(weights)
bias = np.random.rand(1)
print(bias)
lr=0.001

[[0.37454012]
 [0.95071431]]
[0.73199394]


In [90]:
for epoch in range(30000):
  inputs = feature_set

  XW = np.dot(feature_set, weights) + bias

  z=sigmoid(XW)

  error = z-labels

  print(error.sum())

  dcost_dpred = error
  dpred_dz = sigmoid_der(z)

  z_delta = dcost_dpred * dpred_dz
  inputs = feature_set.T
  weights -= lr * np.dot(inputs, z_delta)

  for num in z_delta:
    bias -=lr*num

Streaming output truncated to the last 5000 lines.
0.34246632346444317
0.3424319210924955
0.34239752303869586
0.3423631293022266
0.34232873988233775
0.3422943547782269
0.34225997398911073
0.34222559751425097
0.3421912253527716
0.34215685750401414
0.34212249396708316
0.34208813474128175
0.3420537798257543
0.34201942921980394
0.3419850829225578
0.3419507409333209
0.3419164032512639
0.341882069875611
0.34184774080558666
0.3418134160404249
0.34177909557931396
0.3417447794215336
0.3417104675662058
0.34167616001267764
0.3416418567600432
0.3416075578076395
0.3415732631545775
0.3415389728001812
0.34150468674360257
0.34147040498408404
0.3414361275208479
0.3414018543531427
0.3413675854801176
0.34133332090111224
0.34129906061521775
0.34126480462176656
0.34123055291992604
0.341196305508903
0.3411620623879805
0.34112782355632165
0.3410935890132145
0.3410593587578227
0.3410251327894023
0.34099091110717566
0.34095669371035076
0.3409224805981696
0.3408882717698611
0.3408540672246324
0.3408198669617136

In [91]:
single_point = np.array([23,1])
result = sigmoid(np.dot(single_point, weights)+bias)
print (result)

[0.20761485]
